[package]
name = "hbbs"
version = "1.0.0"
authors = ["open-trade <info@opentradesolutions.com>"]
edition = "2018"
build= "build.rs"

[[bin]]
name = "hbbr"
path = "src/hbbr/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hbb_common = { path = "libs/hbb_common" }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
clap = "2.33"
rust-ini = "0.16"

[build-dependencies]
cc = "1.0"
hbb_common = { path = "libs/hbb_common" }

[workspace]
members = ["libs/hbb_common"]

[dependencies.rocksdb]
default-features = false
features = ["lz4"]
version = "0.15"
