[package]
name = "hbbs"
version = "0.1.0"
authors = ["open-trade <info@opentradesolutions.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-error = "0.2"
hbb_common = { path = "libs/hbb_common" }

[workspace]
members = ["libs/hbb_common"]

